// src/renderer/lib/components/List.tsx
import { BlockType } from '$lib/type/block';
import { Icon } from '@iconify/react';
import { getColor, ColorPalette } from '$lib/utils/color';
import React, { useState, useRef, useEffect } from 'react';
import { useBlocksStore, draggingStore } from '$lib/store';

interface ListProps {
  content: BlockType;
}

const List: React.FC<ListProps> = ({ content }) => {
  const [listWidth, setListWidth] = useState(200);
  const [listHeight, setListHeight] = useState(58);
  const [isFlag, setIsFlag] = useState(false);

  const blockRef = useRef<HTMLDivElement>(null);

  const [isDragging, setIsDragging] = useState(false);
  const blockAddedRef = useRef(false);

  useEffect(() => {
    setIsFlag(content.type === 'flag');
  }, [content.type]);

  const addBlock = () => {
    const newId = Math.random().toString(36).substring(7);
    useBlocksStore.getState().addContent({ ...content, id: newId });
    draggingStore.setState({ id: newId });
    console.log('Added block:', newId);
  };

  const handlePointerDown = () => {
    setIsDragging(true);
    blockAddedRef.current = false;
    window.addEventListener('pointermove', handlePointerMove);
    window.addEventListener('pointerup', handlePointerUp);
  };

  const handlePointerMove = () => {
    if (!blockAddedRef.current) {
      addBlock();
      blockAddedRef.current = true;
    }
  };

  const handlePointerUp = () => {
    window.removeEventListener('pointermove', handlePointerMove);
    window.removeEventListener('pointerup', handlePointerUp);
    setIsDragging(false);
    draggingStore.setState({ id: '' });
  };

  const updateSize = () => {
      if (blockRef.current) {
        setListWidth(blockRef.current.offsetWidth);
        setListHeight(blockRef.current.offsetHeight + 8);
      }
    };
  
    useEffect(() => {
      updateSize();
    }, []);

  return (
    <div
      ref={blockRef}
      className="cancel"
      onPointerDown={handlePointerDown}
      role="button"
      style={{ zIndex: content.zIndex }}
      tabIndex={0}
    >
      <div
        className="relative flex h-12 w-fit cursor-pointer items-center justify-center rounded-md px-2.5 pb-1 align-middle"
        data-id={content.id}
      >
        <div className="absolute left-0 top-0 -z-10 h-0 w-full">
          <svg className="" height={listHeight} role="none" width={listWidth + 2} xmlns="http://www.w3.org/2000/svg">
            <path
              d={isFlag
                ? `M 14 2 L 42 2 L ${listWidth - 14} 2 Q ${listWidth} 2 ${listWidth} 14 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 14 Q 2 2 14 2 Z`
                : `M 4 2 L 14 2 L 14 4 Q 14 8 20 8 L 38 8 Q 42 8 42 4 L 42 2 L ${listWidth - 4} 2 Q ${listWidth} 2 ${listWidth} 4 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 4 Q 2 2 4 2 Z`}
              fill={ColorPalette[getColor(content.type)].bg}
              stroke={ColorPalette[getColor(content.type)].border}
              strokeWidth="2"
              style={{ filter: `drop-shadow(0 4px 0 ${ColorPalette[getColor(content.type)].border})` }}
            ></path>
          </svg>
        </div>
        <div
          className="flex h-full w-full flex-row items-center justify-center gap-4 align-middle"
          style={{ color: ColorPalette[getColor(content.type)].text }}
        >
          <div className="whitespace-nowrap font-bold">{content.title}</div>
          <div className="flex flex-row gap-2 align-middle">
            {content.contents.map((item, index) => (
              <div key={index} className="flex flex-row items-center justify-center gap-1">
                {item.type === 'separator' ? (
                  <div className="h-5 w-[1px] bg-blue-950"></div>
                ) : (
                  <>
                    <div>{item.content.title}</div>
                    <div
                      className="flex items-center justify-center rounded-full border-2 px-2 focus:outline-none"
                      style={{
                        backgroundColor: ColorPalette[getColor(content.type)].text,
                        borderColor: ColorPalette[getColor(content.type)].border,
                      }}
                    >
                      <input
                        type="text"
                        className="text-slate-900 bg-transparent"
                        style={{ width: `${item.content.value.length + 1}ch` }}
                        onChange={(e) => {
                          e.target.style.width = `${e.target.value.length + 1}ch`;
                          setListWidth(blockRef.current!.offsetWidth);
                        }}
                      />
                    </div>
                  </>
                )}
              </div>
            ))}
          </div>
          {isFlag && (
            <button
              className="flex items-center justify-center rounded-full border-2 p-1"
              style={{
                backgroundColor: ColorPalette[getColor(content.type)].text,
                borderColor: ColorPalette[getColor(content.type)].border,
              }}
            >
              <Icon icon="ic:round-flag" className="h-5 w-5 text-green-400" />
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default List;

// src/renderer/lib/block/List.svelte
<script lang="ts">
    import type { BlockType } from '$lib/block/type';
    import { getColor } from '$lib/block/index';
    import { ColorPalette } from '$lib/utils/color';
    import { toast } from 'svelte-sonner';
    import Icon from '@iconify/svelte';
    import { Block } from '$lib/block/class';
    import { BlockStore } from '$lib/block/store';

    export let content: BlockType;

	const blockStore = BlockStore.getInstance();

    $: isFlag = content.type === 'flag';
    $: listWidth = listBlock ? listBlock.clientWidth + 6 : 1000;
    $: listHeight = listBlock ? listBlock.clientHeight + 6 : 60;

    let listBlock: HTMLElement;
    let listField: HTMLInputElement;

    const addBlock = () => {
        const newId = Math.random().toString(36).substring(7);
        const newBlock: Block = Block.createBlock(content, newId, { x: 10, y: 10 });
        blockStore.addBlock(newBlock.block);
    }
</script>

<div
	bind:this={listBlock}
	class="cancel"
	on:pointerdown={() => {
		addBlock();
	}}
	role="button"
	style="z-index: {content.zIndex};"
	tabindex="0"
>
	<div
		class="relative flex h-12 w-fit cursor-pointer items-center justify-center rounded-md px-2.5 pb-1 align-middle"
		data-id={content.id}
	>
		{#if content.connections.input}
			<span
				data-id={content.id}
				class="absolute h-2 w-6"
				style="top: {content.connections.input.y}px; left: {content.connections.input.x}px;"
			></span>
		{/if}
		{#if content.connections.output}
			<span
				data-id={content.id}
				class="absolute h-2 w-6"
				style="bottom: {content.connections.output.y}px; left: {content.connections.output.x}px;"
			></span>
		{/if}
		<div class="absolute left-0 top-0 -z-10 h-0 w-full">
			<svg class="" height={listHeight} role="none" width={listWidth + 2} xmlns="http://www.w3.org/2000/svg">
				<path
					d={isFlag
						? `M 14 2 L 42 2 L ${listWidth - 14} 2 Q ${listWidth} 2 ${listWidth} 14 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 14 Q 2 2 14 2 Z`
						: `M 4 2 L 14 2 L 14 4 Q 14 8 20 8 L 38 8 Q 42 8 42 4 L 42 2 L ${listWidth - 4} 2 Q ${listWidth} 2 ${listWidth} 4 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 4 Q 2 2 4 2 Z`
					}
					fill={ColorPalette[getColor(content.type)].bg}
					stroke={ColorPalette[getColor(content.type)].border}
					stroke-width="2"
					style="filter: drop-shadow(0 4px 0 {ColorPalette[getColor(content.type)].border});"
				></path>
			</svg>
		</div>
		<div
			class="flex h-full w-full flex-row items-center justify-center gap-4 align-middle"
			style="color: {ColorPalette[getColor(content.type)].text};"
		>
			<div class="whitespace-nowrap font-bold">{content.title}</div>
			<div class="flex flex-row gap-2 align-middle">
				{#each content.contents as item}
					{#if item.type === 'separator'}
						<div class="h-5 w-[1px] bg-blue-950"></div>
					{:else if item.type === 'value'}
						<div class="flex flex-row items-center justify-center gap-1.5">
							<div class="whitespace-nowrap">{item.content.title}</div>
							<input
								type="text"
								style="background-color: {ColorPalette[getColor(content.type)].text}; border-color: {ColorPalette[getColor(content.type)].border}; width: calc({Math.max(2, item.content.value.length)}ch + 0.5rem)"
								class="flex h-6 min-w-[2ch] items-center rounded-full border-2 p-0 text-center align-middle text-sm text-blue-950 focus:outline-none"
								bind:value={item.content.value}
								bind:this={listField}
								on:input={() => {
									if (listField) {
										listField.style.width = `${Math.max(2, listField.value.length)}ch`;
										listWidth = listBlock.clientWidth;
									}
								}}
							/>
						</div>
					{/if}
				{/each}
			</div>
			{#if isFlag}
				<button
					on:click={() => {
						//const children = searchAllChildren(content.id);
						//formatOutput(children);
						//window.navigator.clipboard.writeText($output);
						toast.success('Output copied to clipboard');
					}}
					class="flex items-center justify-center rounded-full border-2 p-1"
					style={`border-color: ${ColorPalette[getColor(content.type)].border}; background-color: ${ColorPalette[getColor(content.type)].text};`}
				>
					<Icon icon="ic:round-flag" class="h-5 w-5 text-green-400" />
				</button>
			{/if}
		</div>
	</div>
</div>
