// src/renderer/lib/components/List.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import type { Block } from '$lib/types';
	import { output, workspace } from '$lib/stores';
	import { ColorPalette } from '$lib/utils/color';
	import { addBlock, formatOutput } from '$lib/utils/block';
	import { toast } from 'svelte-sonner';
	import { onMount } from 'svelte';

	export let content: Block;

	let block: HTMLElement;
	let field: HTMLInputElement;
	let width: number = 1000;
	let height: number = 60;
	let clientX: number = 0;
	let clientY: number = 0;

	$: width = block ? block.clientWidth + 6 : 1000;
	$: height = block ? block.clientHeight + 6 : 60;
	$: isFlag = content.type === 'flag';

	const searchAllChildren = (id: string): Block[] => {
		const children: Block[] = [];
		$workspace.blocks.forEach((block) => {
			if (block.parentId === id) {
				children.push(block);
				children.push(...searchAllChildren(block.id));
			}
		});
		return children;
	};

	let isDragging = false;

	let position = { x: 0, y: 0 };

	onMount(() => {
		if (block) {
			position = { x: block.offsetLeft, y: block.offsetTop };
		}
	});
</script>

<svelte:window on:mousemove={(e) => {
	clientX = e.clientX;
	clientY = e.clientY;
}} />

<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
	bind:this={block}
	class="cancel"
	on:click={() => {
		addBlock(content);
	}}
	role="button"
	style="z-index: {content.zIndex};"
	tabindex="0"
>
	<div
		class="relative flex h-12 w-fit cursor-pointer items-center justify-center rounded-md px-2.5 pb-1 align-middle"
		data-id={content.id}
	>
		{#if content.connections.input}
			<span
				data-id={content.id}
				class="input absolute left-4 top-0 h-2 w-6"
			></span>
		{/if}
		{#if content.connections.output}
			<span
				data-id={content.id}
				class="input absolute bottom-0 left-4 h-2 w-6"
			></span>
		{/if}
		<div class="absolute left-0 top-0 -z-10 h-0 w-full">
			<svg class="" {height} role="none" width={width + 2} xmlns="http://www.w3.org/2000/svg">
				<path
					d={isFlag
						? `M 14 2 L 42 2 L ${width - 14} 2 Q ${width} 2 ${width} 14 L ${width} ${height - 18} Q ${width} ${height - 14} ${width - 4} ${height - 14} L 40 ${height - 14} L 40 ${height - 10} Q 40 ${height - 8} 36 ${height - 8} L 20 ${height - 8} Q 16 ${height - 8} 16 ${height - 10} L 16 ${height - 14} L 4 ${height - 14} Q 2 ${height - 14} 2 ${height - 18} L 2 14 Q 2 2 14 2 Z`
						: `M 4 2 L 14 2 L 14 4 Q 14 8 20 8 L 38 8 Q 42 8 42 4 L 42 2 L ${width - 4} 2 Q ${width} 2 ${width} 4 L ${width} ${height - 18} Q ${width} ${height - 14} ${width - 4} ${height - 14} L 40 ${height - 14} L 40 ${height - 10} Q 40 ${height - 8} 36 ${height - 8} L 20 ${height - 8} Q 16 ${height - 8} 16 ${height - 10} L 16 ${height - 14} L 4 ${height - 14} Q 2 ${height - 14} 2 ${height - 18} L 2 4 Q 2 2 4 2 Z`
					}
					fill={ColorPalette[content.color].bg}
					stroke={ColorPalette[content.color].border}
					stroke-width="2"
					style="filter: drop-shadow(0 4px 0 {ColorPalette[content.color].border});"
				></path>
			</svg>
		</div>
		<div
			class="flex h-full w-full flex-row items-center justify-center gap-4 align-middle"
			style="color: {ColorPalette[content.color].text};"
		>
			<div class="whitespace-nowrap font-bold">{content.title}</div>
			<div class="flex flex-row gap-2 align-middle">
				{#each content.contents as item}
					{#if item === 'space'}
						<div class="h-5 w-[1px] bg-blue-950"></div>
					{:else}
						<div class="flex flex-row items-center justify-center gap-1.5">
							<div class="whitespace-nowrap">{item.text}</div>
							<input
								type="text"
								style="background-color: {ColorPalette[content.color].text}; border-color: {ColorPalette[content.color].border}; width: calc({Math.max(2, item.value.length)}ch + 0.5rem)"
								class="flex h-6 min-w-[2ch] items-center rounded-full border p-0 text-center align-middle text-sm text-blue-950 focus:outline-none"
								bind:value={item.value}
								bind:this={field}
								on:input={() => {
									if (field) {
										field.style.width = `${Math.max(2, field.value.length)}ch`;
										width = block.clientWidth;
									}
								}}
							/>
						</div>
					{/if}
				{/each}
			</div>
			{#if isFlag}
				<button
					on:click={() => {
						const children = searchAllChildren(content.id);
						formatOutput(children);
						window.navigator.clipboard.writeText($output);
						toast.success('Output copied to clipboard');
					}}
					class="flex items-center justify-center rounded-full border-2 p-1"
					style={`border-color: ${ColorPalette[content.color].border}; background-color: ${ColorPalette[content.color].text};`}
				>
					<Icon icon="ic:round-flag" class="h-5 w-5 text-green-400" />
				</button>
			{/if}
		</div>
	</div>
</div>

// src/renderer/lib/components/List.tsx
import { BlockType } from '$lib/block/type';
import { Icon } from '@iconify/react';
import { ColorPalette, getColor } from '$lib/utils/color';
import React, { useEffect, useRef, useState } from 'react';
import { useBlocksStore } from '$lib/store';
import { BlockStore } from '$lib/block/store';

interface ListProps {
	content: BlockType;
}

const List: React.FC<ListProps> = ({ content }) => {
	const [listWidth, setListWidth] = useState(200);
	const [listHeight, setListHeight] = useState(58);
	const [isFlag, setIsFlag] = useState(false);

	const { setDraggingBlock } = useBlocksStore();

	const blockRef = useRef<HTMLDivElement>(null);

	const blockAddedRef = useRef(false);

	useEffect(() => {
		setIsFlag(content.type === 'flag');
	}, [content.type]);

	const addBlock = (event: PointerEvent) => {
		const blockStore = BlockStore.getInstance();
		const newId = blockStore.addBlock(content);
		const offset = blockRef.current!.getBoundingClientRect();
		setDraggingBlock(newId, { x: event.clientX - offset.left, y: event.clientY - offset.top });
	};

	const handlePointerDown = () => {
		blockAddedRef.current = false;
		window.addEventListener('pointermove', handlePointerMove);
		window.addEventListener('pointerup', handlePointerUp);
	};

	const handlePointerMove = (event: PointerEvent) => {
		if (!blockAddedRef.current) {
			addBlock(event);
			blockAddedRef.current = true;
		}
	};

	const handlePointerUp = () => {
		window.removeEventListener('pointermove', handlePointerMove);
		window.removeEventListener('pointerup', handlePointerUp);
	};

	const updateSize = () => {
		if (blockRef.current) {
			setListWidth(blockRef.current.offsetWidth);
			setListHeight(blockRef.current.offsetHeight + 8);
		}
	};

	useEffect(() => {
		updateSize();
	}, []);

	return (
		<div
			ref={blockRef}
			className="cancel"
			onPointerDown={handlePointerDown}
			role="button"
			style={{ zIndex: content.zIndex }}
			tabIndex={0}
		>
			<div
				className="relative flex h-12 w-fit cursor-pointer items-center justify-center rounded-md px-2.5 pb-1 align-middle"
				data-id={content.id}
			>
				<div className="absolute left-0 top-0 -z-10 h-0 w-full">
					<svg
						className=""
						height={listHeight}
						role="none"
						width={listWidth + 2}
						xmlns="http://www.w3.org/2000/svg"
					>
						<path
							d={
								isFlag
									? `M 14 2 L 42 2 L ${listWidth - 14} 2 Q ${listWidth} 2 ${listWidth} 14 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 14 Q 2 2 14 2 Z`
									: `M 4 2 L 14 2 L 14 4 Q 14 8 20 8 L 38 8 Q 42 8 42 4 L 42 2 L ${listWidth - 4} 2 Q ${listWidth} 2 ${listWidth} 4 L ${listWidth} ${listHeight - 18} Q ${listWidth} ${listHeight - 14} ${listWidth - 4} ${listHeight - 14} L 40 ${listHeight - 14} L 40 ${listHeight - 10} Q 40 ${listHeight - 8} 36 ${listHeight - 8} L 20 ${listHeight - 8} Q 16 ${listHeight - 8} 16 ${listHeight - 10} L 16 ${listHeight - 14} L 4 ${listHeight - 14} Q 2 ${listHeight - 14} 2 ${listHeight - 18} L 2 4 Q 2 2 4 2 Z`
							}
							fill={ColorPalette[getColor(content.type)].bg}
							stroke={ColorPalette[getColor(content.type)].border}
							strokeWidth="2"
							style={{
								filter: `drop-shadow(0 4px 0 ${ColorPalette[getColor(content.type)].border})`
							}}
						></path>
					</svg>
				</div>
				<div
					className="flex h-full w-full flex-row items-center justify-center gap-4 align-middle"
					style={{ color: ColorPalette[getColor(content.type)].text }}
				>
					<div className="whitespace-nowrap font-bold">{content.title}</div>
					<div className="flex flex-row gap-2 align-middle">
						{content.contents.map((item, index) => (
							<div key={index} className="flex flex-row items-center justify-center gap-1">
								{item.type === 'separator' ? (
									<div className="h-5 w-[1px] bg-blue-950"></div>
								) : (
									<>
										<div>{item.content.title}</div>
										<div
											className="flex items-center justify-center rounded-full border-2 px-2 focus:outline-none"
											style={{
												backgroundColor: ColorPalette[getColor(content.type)].text,
												borderColor: ColorPalette[getColor(content.type)].border
											}}
										>
											<input
												type="text"
												className="bg-transparent text-slate-900"
												style={{ width: `${item.content.value.length + 1}ch` }}
												onChange={(e) => {
													e.target.style.width = `${e.target.value.length + 1}ch`;
													setListWidth(blockRef.current!.offsetWidth);
												}}
											/>
										</div>
									</>
								)}
							</div>
						))}
					</div>
					{isFlag && (
						<button
							className="flex items-center justify-center rounded-full border-2 p-1"
							style={{
								backgroundColor: ColorPalette[getColor(content.type)].text,
								borderColor: ColorPalette[getColor(content.type)].border
							}}
						>
							<Icon icon="ic:round-flag" className="h-5 w-5 text-green-400" />
						</button>
					)}
				</div>
			</div>
		</div>
	);
};

export default List;
